name: build-xcode-project

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Test xcode project
      run: xcodebuild test -scheme GithubActionsSample -destination "platform=iOS Simulator,name=iPhone 11,OS=13.1"
