name: build-xcode-project

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Echo variable
      run: echo ${{ secrets.secretValue }}
    - name: Install cocoapods-keys
      run: gem install cocoapods-keys
    - name: Inject secrets
      run: pod keys set SecretValue ${{ secrets.secretValue }}
    - name: Generate signed source code
      run: pod install
    - name: Test xcode project
      run: xcodebuild test -workspace "GithubActionsSample.xcworkspace" -scheme GithubActionsSample -destination "platform=iOS Simulator,name=iPhone 11"
